order-service:
  url: http://order-service:8080/api/v2/orders/

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://product-db:3307/product_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect