spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java
    username: pg
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true