product-service-v1:
  url: http://localhost:8081/api/products/

product-service-v2:
  url: http://localhost:8081/api/v2/products/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect