spring:
  #  profile: inMemory
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

jwt:
  config:
    secret: 'c2VjcmV0X3NlY3JldF9zZWNyZXRfc2VjcmV0X3NlY3JldA=='
    tokenExpirationMs: 60_000
    refreshTokenExpirationMs: 3600_000
    #  15min - 2h
    #  1min = 60s = 60_000ms
    # 10min = 600_000ms
    # 60 min 3600_000ms
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect